name = "MyPortfolio"
license = "Apache License 2.0"
licenselink = "//github.com/2-REC/hugo-myportfolio-theme/blob/master/LICENSE"
description = "A portfolio HUGO theme for developers and creatives."
homepage = "https://derekseverin.netlify.com/"
tags = ["portfolio", "blog", "responsive", "personal", "business", "projects", "bootstrap"]
features = ["blog", "responsive", "dynamic content", "substitutable strings"]
min_version = 0.44

[author]
  name = "2-REC"
  homepage = "//github.com/2-REC"

[original]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman"
  repo = "//github.com/digitalcraftsman/hugo-creative-theme"
